import { SignInButton, UserButton } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import styles from './index.module.css';

import { Switch } from '@mantine/core';
import { api } from '~/utils/api';

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' });

  console.log(hello);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Switch label="I agree to sell my privacy" />
          <SignInButton />
          <UserButton />
        </div>
      </main>
    </>
  );
};

export default Home;
