import { type NextPage } from 'next';
import Head from 'next/head';

import { api } from '~/utils/api';

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' });

  console.log(hello);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat
          dolores excepturi illum, soluta id sint eos ea distinctio quod in
          sunt? Aspernatur beatae rem unde ipsam maxime, quibusdam laudantium.
          Id? Cupiditate consectetur soluta similique corporis, architecto
          voluptas quis ipsam veritatis error fugit dolore at alias quae in
          harum nam quo id nemo nostrum sunt delectus impedit iure tenetur! Sed,
          impedit! Enim veniam vel delectus facere fugit beatae incidunt illo
          quis amet voluptates quae numquam tempore in vitae, soluta consectetur
          obcaecati. Aut dignissimos odio omnis porro earum cumque libero
          voluptatem tempora? Nostrum dolorum dolore vel debitis expedita, rerum
          molestiae aliquam necessitatibus harum eum perferendis enim neque
          voluptates molestias quis dolorem magni ipsam maxime ducimus ab. Vel,
          itaque? Accusantium odio enim magni! Omnis, voluptatibus iste fugit,
          assumenda fuga repellat soluta ratione temporibus explicabo
          dignissimos neque labore pariatur nobis. Veniam quas dolorem voluptas
          optio vel, dolores eligendi, sint dignissimos, sunt at nam magni.
        </div>
      </main>
    </>
  );
};

export default Home;
