import { ActionIcon, Flex, Grid, Text, Title } from '@mantine/core';
import { IconPlus } from '@tabler/icons-react';

import type { NextPage } from 'next';
import Head from 'next/head';
import { PlayerCard } from '~/components/PlayersPage/PlayerCard';

const players = [
  { fname: 'Jan', lname: 'Motak' },
  { fname: 'Anna', lname: 'Kowalski' },
  { fname: 'Emma', lname: 'Lee' },
  { fname: 'David', lname: 'Johnson' },
  { fname: 'Sara', lname: 'Gonzalez' },
  { fname: 'Max', lname: 'Smith' },
  { fname: 'Maria', lname: 'Garcia' },
  { fname: 'Jack', lname: 'Brown' },
  { fname: 'Olivia', lname: 'Davis' },
  { fname: 'Alex', lname: 'Martinez' },
  { fname: 'Sophia', lname: 'Wilson' },
  { fname: 'Luke', lname: 'Taylor' },
  { fname: 'Isabella', lname: 'Hernandez' },
  { fname: 'Noah', lname: 'Thomas' },
  { fname: 'Emily', lname: 'Moore' },
];

const League: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex gap={10} align="center">
          <Title order={1} c="white" mb={2}>
            Players
          </Title>
          <ActionIcon variant="light" color="gray.1" radius="md">
            <IconPlus size="1rem" />
          </ActionIcon>
        </Flex>

        <Text fz="sm">List of players in league and their administration</Text>
        <Grid sx={{ paddingTop: '2rem' }}>
          {players.map(player => (
            <Grid.Col md={6} lg={3} key={`card-${player.lname}`}>
              <PlayerCard firstName={player.fname} lastName={player.lname} />
            </Grid.Col>
          ))}
        </Grid>
      </main>
    </>
  );
};

export default League;
